name: PetalDeskGit

on : [push] 

jobs:
  build:
    name: Building Petal...
    runs-on: ubuntu-latest
    timeout-minutes: 129600
    
    steps:
      - name: Set settings...
        uses: "actions/checkout@v1"
      - name: Venv options setting
        run: |
          pip install python-Levenshtein
          pip install auto-gptq --extra-index-url https://huggingface.github.io/autogptq-index/whl/cu118/  # Use cu117 if on CUDA 11.7
          pip install -r $GITHUB_WORKSPACE/requirements.txt
      - name: Venv starting...
        env:
          CI: true
          DISCORDTOKEN:  ${{secrets.DISCORDTOKEN}}
        run: |
          export DISCORDTOKEN=${{secrets.DISCORDTOKEN}}
          echo DISCORDTOKEN=${{secrets.DISCORDTOKEN}} > .env
          npm install discord.js
          npm install python-shell
          node $GITHUB_WORKSPACE/discord.js "$DISCORDTOKEN"
