name: PetalDeskGit

on:
  workflow_dispatch:

jobs:
  build:
    name: Building Petal...
    runs-on: ubuntu-latest
    timeout-minutes: 129600
    
    steps:
      - name: Set settings...
        uses: "actions/checkout@v1"
      - name: Venv options setting
        run: |
          pip install python-Levenshtein
          pip install auto-gptq --extra-index-url https://huggingface.github.io/autogptq-index/whl/cu118/  # Use cu117 if on CUDA 11.7
          pip install -r $GITHUB_WORKSPACE/requirements.txt
          
      - name: Venv starting...
        run: |
          echo ${{ secrets.DISCORDTOKEN }} > .env
          export DiscordToken=${{ secrets.DISCORDTOKEN }}
          npm install discord.js
          npm install python-shell
      - name: Petal starting...
        run: |
          node $GITHUB_WORKSPACE/discord.js ${{ secrets.DISCORDTOKEN }}
