name: PetalDeskGit

on:
  workflow_dispatch:

jobs:
  build:
    name: Building Petal...
    runs-on: ubuntu-latest
    
    
    steps:
      - uses: actions/checkout@v3
      - name: Downloading & Installing Essentials
        run: |
          pip install virtualenv
          virtualenv venv
          pip install -r $GITHUB_WORKSPACE/requirements.txt
      - name: Venv options setting
        run: |
          source venv/bin/activate
          python $GITHUB_WORKSPACE/main.py 
