name: PetalDeskGit

on:
  workflow_dispatch:

jobs:
  build:
    name: Building Petal...
    runs-on: PetalAI running
    
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          cmd /c ls
          Invoke-WebRequest -Uri "https://drive.google.com/drive/folders/1MtdWSC6WQgFgY2i0Gdg49LpHK9a9FoaF?usp=drive_link"
          pip install -r requirements
          

      - name: Download Venv emulate
        run: pip install virtualenv

      - name: Log In PetalAI
        run: |
          cmd source venv/Scripts/activate
          python main.py   
