name: PetalDeskGit

on:
  workflow_dispatch:

jobs:
  build:
    name: Building Petal...
    runs-on: windows-latest
    
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          curl requirements.txt https://www.dropbox.com/scl/fi/zf3mnckz8x4k04ab9cmwn/requirements.txt?rlkey=rg9ekmw4rswcubk26er9e2lnl&dl=0
          curl dataset.json https://www.dropbox.com/scl/fi/zf3mnckz8x4k04ab9cmwn/requirements.txt?rlkey=rg9ekmw4rswcubk26er9e2lnl&dl=0
          curl neiro.py https://www.dropbox.com/scl/fi/zf3mnckz8x4k04ab9cmwn/requirements.txt?rlkey=rg9ekmw4rswcubk26er9e2lnl&dl=0
          curl main.py https://www.dropbox.com/scl/fi/zf3mnckz8x4k04ab9cmwn/requirements.txt?rlkey=rg9ekmw4rswcubk26er9e2lnl&dl=0
      - name: Download Venv emulate
        run: |
          pip install virtualenv
          cmd /c dir
      - name: Venv options setting
        run: |
          cmd source venv/Scripts/activate
          pip install -r requirements.txt
          python main.py 
