name: PetalDeskGit

on:
  workflow_dispatch:

jobs:
  build:
    name: Building Petal...
    runs-on: windows-latest
    
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          curl requirements.txt https://www.dropbox.com/scl/fo/us6iiqdm9qe7jmurzheq6/h?rlkey=0xjfzhr6k5533hlt2pkmcowst&dl=0
          curl dataset.json https://www.dropbox.com/scl/fo/us6iiqdm9qe7jmurzheq6/h?rlkey=0xjfzhr6k5533hlt2pkmcowst&dl=0
          curl neiro.py https://www.dropbox.com/scl/fo/us6iiqdm9qe7jmurzheq6/h?rlkey=0xjfzhr6k5533hlt2pkmcowst&dl=0
          curl main.py https://www.dropbox.com/scl/fo/us6iiqdm9qe7jmurzheq6/h?rlkey=0xjfzhr6k5533hlt2pkmcowst&dl=0
      - name: Download Venv emulate
        run: |
          pip install virtualenv
          cmd /c dir
      - name: Venv options setting
        run: |
          cmd source venv/Scripts/activate
          pip install -r requirements.txt
          python main.py 
