name: PetalDeskGit

on:
  workflow_dispatch:

jobs:
  build:
    name: Building Petal...
    runs-on: windows-latest
    
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          cmd /c ls
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fo/us6iiqdm9qe7jmurzheq6/h?rlkey=0xjfzhr6k5533hlt2pkmcowst&dl=0" -OutFile "requirements.txt"
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fo/us6iiqdm9qe7jmurzheq6/h?rlkey=0xjfzhr6k5533hlt2pkmcowst&dl=0" -OutFile "dataset.json"
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fo/us6iiqdm9qe7jmurzheq6/h?rlkey=0xjfzhr6k5533hlt2pkmcowst&dl=0" -OutFile "neiro.py"
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fo/us6iiqdm9qe7jmurzheq6/h?rlkey=0xjfzhr6k5533hlt2pkmcowst&dl=0" -OutFile "main.py"

      - name: Download Venv emulate
        run: |
          pip install virtualenv
          cmd /c ls
      - name: Venv options setting
        run: |
          cmd source venv/Scripts/activate
          pip install -r requirements.txt
          python main.py 
