name: PetalDeskGit

on:
  workflow_dispatch:

jobs:
  build:
    name: Building Petal...
    runs-on: ubuntu-latest
    timeout-minutes: 129600
    
    steps:
      - uses: actions/checkout@v3
      - name: Downloading & Installing Essentials
        run: |
          pip install virtualenv
          
      - name: Venv options setting
        run: |
          virtualenv venv
          source venv/bin/activate
          pip install python-Levenshtein
          pip install -r $GITHUB_WORKSPACE/requirements.txt
          
      - name: Venv starting...
        run: |
          source venv/bin/activate
          echo ${{ secrets.DISCORDTOKEN }}
          export DiscordToken=${{ secrets.DISCORDTOKEN }}
          python $GITHUB_WORKSPACE/main.py ${{ secrets.DISCORDTOKEN }}
