name: PetalDeskGit

on:
  workflow_dispatch:

jobs:
  build:
    name: Building Petal...
    runs-on: ubuntu-latest
    
    
    steps:
      - uses: actions/checkout@v3
      - name: Downloading & Installing Essentials
        run: pip install -r $GITHUB_WORKSPACE/requirements.txt
        
      - name: Download Venv emulate
        run: |
          pip install virtualenv
          cmd /c dir
      - name: Venv options setting
        run: |
          cmd source venv/Scripts/activate
          more requirements.txt
          python $GITHUB_WORKSPACE/main.py 
