name: PetalDeskGit

on:
  workflow_dispatch:

jobs:
  build:
    name: Building Petal...
    runs-on: ubuntu-latest
    
    
    steps:
      - uses: actions/checkout@v3
      - name: Downloading & Installing Essentials
        run: |
          pip install virtualenv
          
      - name: Venv options setting
        run: |
          virtualenv venv
          source venv\Scripts\activate
          pip install python-Levenshtein
          pip install -r $GITHUB_WORKSPACE/requirements.txt
          
      - name: Venv starting...
        env: # Set the secret as an input
          DISCORDTOKEN: ${{ secrets.Discordtoken }}
        run: |
          source venv\Scripts\activate
          python os.putenv DiscordToken, ${{ secrets.Discordtoken }}
          python $GITHUB_WORKSPACE/main.py 
